name: castorstatistics
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter_launcher_icons: any
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  http: any
  latlong: any
  flutter_map: any
  webview_flutter: ^2.0.2
  number_display: any
  flutter_map_marker_cluster: any
  flutter:
    sdk: flutter

  async: ^2.1.0


  cupertino_icons: ^1.0.2
  flutter_echarts: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pics/
    - assets/images/profile.png


